import { isbot } from "isbot";
import { renderToReadableStream } from "react-dom/server";
import type { AppLoadContext, EntryContext } from "react-router";
import { ServerRouter } from "react-router";

/**
 * Server-side rendering entry point
 *
 * Steps (ref: https://zenn.dev/coji/articles/react-router-v7-internal-flow#%E8%B5%B7%E5%8B%95%E3%81%8B%E3%82%89%E5%88%9D%E5%9B%9E%E8%A1%A8%E7%A4%BA%E3%81%BE%E3%81%A7%E3%81%AE%E9%81%93%E3%81%AE%E3%82%8A-(ssr%E3%83%95%E3%83%AD%E3%83%BC))
 * (0. Run middlewares)
 * 1. [server] [entrypoint of React Router] `fetch` function (workers/app.ts)
 * 2. [server] route matching & run loader (app/rotues.ts & matched loaders on all matched routes)
 * 3. [server] server-side rendering (SSR) (entry.server.tsx)
 * 4. [server] send response, including rendered HTML stream, headers, etc., to client
 * --- network ---
 * 5. [client] receive response
 * 6. [client] parse HTML and create DOM tree / load CSS and JavaScript modules
 * 7. [client] run client entry point (app/entry.client.tsx) from `<script type="module">` from `<Scripts />` in root.tsx
 * 8. [client] hydration (app/entry.client.tsx)
 *   - call `hydrateRoot` in app/entry.client.tsx
 *   - React compares the HTML generated by SSR to the components tree generated by CSR
 *   - then attach event listeners to the DOM elements and make DOM interactive
 * 9. [client] now, application is fully interactive
 * 10. [client] run `useEffect`, `<ScrollRestoration />` if necessary
 * (0. Run middlewares)
 */
export default async function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  routerContext: EntryContext,
  _loadContext: AppLoadContext,
) {
  console.info("[entry.server] handleRequest");

  let shellRendered = false;
  const userAgent = request.headers.get("user-agent");

  const body = await renderToReadableStream(
    <ServerRouter context={routerContext} url={request.url} />,
    {
      onError(error: unknown) {
        responseStatusCode = 500;
        // Log streaming rendering errors from inside the shell.  Don't log
        // errors encountered during initial shell rendering since they'll
        // reject and get logged in handleDocumentRequest.
        if (shellRendered) {
          console.error(error);
        }
      },
    },
  );
  shellRendered = true;

  // Ensure requests from bots and SPA Mode renders wait for all content to load before responding
  // https://react.dev/reference/react-dom/server/renderToPipeableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation
  if ((userAgent && isbot(userAgent)) || routerContext.isSpaMode) {
    await body.allReady;
  }

  responseHeaders.set("Content-Type", "text/html");
  return new Response(body, {
    headers: responseHeaders,
    status: responseStatusCode,
  });
}
